spring:
  application:
    name: notification-service
  cloud:
    function:
      definition: processOrder
    stream:
      bindings:
        processOrder-in-0:
          destination: order-events
          group: notification-group
      kafka:
        binder:
          brokers: localhost:9092
        consumer:
          group-id: notification-group
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          auto-offset-reset: earliest

server:
  port: 8082

product:
  topic:
    name: product-events
