server:
  port: 8081

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

product:
  topic:
    name: product-events
